### ISSUE TITLE
Identity without a nickname is not correctly reloaded.

### ISSUE THREAD

**Issue by mrbesen** [landave/TeamSpeakHasher#1]
Steps to recreate:

- Add a Identity with a Publickey and no nickname.
- Run `TeamSpeakHasher compute` with this identity
- After it started computation so cancel it by Pressing CTL + C
- try to continue Computation by re-run `TeamSpeakHasher compute`

Expected behavior:
- List all Identitys to chose From

Actual behavior:
- Error is displayed: Error: Please add a public key first.

workaround: open the config file (tshasher.ini) and enter a Valid nickname.

**Comment by landave** [comment]
Thanks for reporting this bug. It has been fixed in 933a431078f76975319e8503d51d3ce6fb9b2bd9.
