### ISSUE TITLE
Level 32 to 33: after reimport only level 1

### ISSUE THREAD

**Issue by Perflyst** [landave/TeamSpeakHasher#11]
Start counter: `2149004738`

`^CStopped at counter: 29528679424`
Added `identity="29528679424V`

Reimported 

![Level Counter](https://user-images.githubusercontent.com/26308977/40579724-70c18934-612e-11e8-9fa9-7079f3c30f1f.png)

Also tried with a new id. Exported with level 8, instantly jumped to level 36.
Reimported: Level 0

Not the same as #6, I have not escaped `/`

**Comment by landave** [comment]
Please present a full example of this (generate an identity for testing purposes only, so that you can paste the full private key.). What is the content of the ini file? What is the content of tshasher.ini?

**Comment by Perflyst** [comment]
`$ cat testid.ini`
> [Identity]
id=test-id
identity="214VAZ95cHJvTRZpBGMhzux8srGvXixeLWMJXl4XB1V1cF5QdldBYFZBGjNwJCFdKW9/AmdSVBtkVShSZH0Jc2hnRWZwYUN3PWoAKhdlUVEbSiJZeWd2HV1xIHkADVUEUWZAFV5EUUlkZmVBaUVBN25naytjSW8rVWxaVGViMjR1V0dtMUFsNTl5b1B6a3NWMEtJdkVDYyszbz0="
nickname=test-id
phonetic_nickname=

`$ ./TSIdentityTool read testid.ini`
> Public key: MEwDAgcAAgEgAiAJ1kS7kKR9gjv66DEk5AcvSdvxPBBDhMZNaRcf+VfN7QIhAPWwVAQsCXS0KsT50z+GhIPCyhBBNd8b52UppnrbIdfe
Public key length (Base64): 104
Fingerprint: Md/5xn2tljfBNVC9x5t3Q6tWgvE=
Curve name: ECC-256 (NIST)
Curve size (octets): 32
Current security level: 10 (with counter=214)

`$ ./TeamSpeakHasher add -publickey MEwDAgcAAgEgAiAJ1kS7kKR9gjv66DEk5AcvSdvxPBBDhMZNaRcf+VfN7QIhAPWwVAQsCXS0KsT50z+GhIPCyhBBNd8b52UppnrbIdfe -startcounter 214`
> Public key has been added successfully.

`$ cat tshasher.ini`
> [identity]
nickname=
identity=MEwDAgcAAgEgAiAJ1kS7kKR9gjv66DEk5AcvSdvxPBBDhMZNaRcf+VfN7QIhAPWwVAQsCXS0KsT50z+GhIPCyhBBNd8b52UppnrbIdfe
currentcounter=214
bestcounter=214

`$ ./TeamSpeakHasher compute`
wait some time
> Running time: 2.872630 min
Device Baffin[0]:
  Global/Local work size: 65536/64
  Current speed: 101.883450 MHash/s
  Average speed: 159.250802 MHash/s
  Scheduling: 2.40198 Kernels/s
Current speed [total]: 101.883450 MHash/s
Average speed [total]: 159.250802 MHash/s
Estimated time until slow phase: 2726.351868 h
Security level: 34 (with counter=23669655774)
Estimated time until level 35: 5.620759 min
Current counter: 27515413504
^CStopped at counter: 27515413504
The progress has been saved successfully

edit .ini export file
`$ cat testid.ini`
> [Identity]
id=test-id
identity="27515413504VAZ95cHJvTRZpBGMhzux8srGvXixeLWMJXl4XB1V1cF5QdldBYFZBGjNwJCFdKW9/AmdSVBtkVShSZH0Jc2hnRWZwYUN3PWoAKhdlUVEbSiJZeWd2HV1xIHkADVUEUWZAFV5EUUlkZmVBaUVBN25naytjSW8rVWxaVGViMjR1V0dtMUFsNTl5b1B6a3NWMEtJdkVDYyszbz0="
nickname=test-id
phonetic_nickname=

reimport via teamspeak gui
-> security level 1

**Comment by landave** [comment]
You need to take the counter that corresponds to the security level, i.e., 23669655774. The current counter just stores the progress in case you want to continue at a later time.

**Comment by Perflyst** [comment]
Facepalm, sorry!
