### ISSUE TITLE
Getting errors while make all

### ISSUE THREAD

**Issue by h1rule** [landave/TeamSpeakHasher#12]
`fuckedup@ubuntu:~/TeamSpeakHasher# make all
g++ -std=c++11 -Wall -Iinclude   -c -o TunedParameters.o TunedParameters.cpp
TunedParameters.cpp: In static member function ‘static TunedParameters TunedParameters::parse(const string&)’:
TunedParameters.cpp:102:15: error: ‘invalid_argument’ is not a member of ‘std’
         throw std::invalid_argument("Tuned parameter section is invalid.");
               ^
TunedParameters.cpp:112:11: error: ‘invalid_argument’ is not a member of ‘std’
     throw std::invalid_argument("Tuned parameter section is invalid.");
           ^
make: *** [TunedParameters.o] Error 1
`

**Comment by landave** [comment]
Make sure you are using gcc version 4.9.x or later. If that does not help, try to add the following line at the top of `TunedParameters.cpp`:

`#include <stdexcept>`

**Comment by landave** [comment]
Make sure you have OpenCL installed for your graphics card (AMD, Nvidia, or Intel). Then, ensure that the OpenCL library is accessible at a known library location. For example, if the library is at `/usr/lib/x86_64-linux-gnu/libOpenCL.so.1`, you may want to set the following symlink:
`sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so`

Note that the issue you are facing now has nothing to do with TeamSpeakHasher. It is just a matter of setting up OpenCL. I recommend you search the web for more information on how to do this.

**Comment by landave** [comment]
No, OpenCL works on servers just as well. Again: You need to setup OpenCL on your system. Did you do this? If yes, what exactly did you install? What GPU are you using?

**Comment by Bluscream** [comment]
Do servers even have a GPU?

**Comment by h1rule** [comment]
Thats what i mean. 

I made this steps, but make all at the end of the steps dont work.

https://www.wikihow.com/Install-Mesa-(OpenGL)-on-Linux-Mint

Do you guys maybe have some alternative step by step guide or installer script?

**Comment by h1rule** [comment]
Its all for Windows! I want to run it on my Dedicated Linux Root. :-D

**Comment by landave** [comment]
> https://www.wikihow.com/Install-Mesa-(OpenGL)-on-Linux-Mint
The URL you posted is about OpenGL, not OpenCL. What GPU does your server have?

**Comment by h1rule** [comment]
It does not have any.

**Comment by landave** [comment]
So you don't have a proper GPU that supports OpenCL. Quote from the FAQ:

> Can I use my CPU to increase the security level?
Currently, only GPUs are supported. This is mainly due to the current code not being vectorized properly. However, OpenCL also supports CPUs. You can try to change DEV_TYPE in TSHasherContext.h to CL_DEVICE_TYPE_CPU.

Note, moreover, that even though you could modify TeamSpeakHasher to run OpenCL on a CPU, this hardly makes any sense. It will be at least 1000 times (!!) slower than running it on a modern GPU.

**Comment by h1rule** [comment]
Shit, ok thanks! :)

**Comment by landave** [comment]
Presumably, it will be a bit faster, but most likely not more than a single-digit integer factor. So I would still consider this a stupid thing to do.

If you absolutely want to increase your security level and have no access to a decent GPU, I would recommend renting a GPU-server from a cloud hoster for a couple of hours (during which you can compute what it would take your CPU years (!!) to compute).
