### ISSUE TITLE
Problem with Initializing OpenCL on Linux

### ISSUE THREAD

**Issue by MrPresidentWhite** [landave/TeamSpeakHasher#15]
I can't get this to run on my linux server... Can you maybe give me the compiled version for windows?
![Screenshot_238](https://user-images.githubusercontent.com/38688739/72036011-d26d8780-3299-11ea-8018-2df2ba597304.png)

**Comment by landave** [comment]
Just use Visual Studio to compile it yourself (have a look at the readme).
