### ISSUE TITLE
GPU load drops from 100% to 1%, hash rate increases from 8.5GH/s to 42GH/s

### ISSUE THREAD

**Issue by Genhanktsti** [landave/TeamSpeakHasher#16]
My GPU Usage start out at 100%, hashing rate roundabout 8,5GH/s.
After some time I noticed that the usage has, according to HWMonitor, dropped to 0% to 1%.
The temperature decreased from 75°C to 55°C with the fans turned off.
THe hashing rate increased to 42GH/s.
I'm now running 42GH/s twice (in parallel).

How?

**Comment by Genhanktsti** [comment]
I can even run 4 instances in parallel each claiming to achieve 42GH/s. The GPU usage sits at roughly 2% to 3%.
I don't think it has reached any new leves while showing that hashing rate.
Accordingly, I think that, even though the counter is indeed increasing at a rate of roughly 42 * 10^9 per second, the program doesn't really compute anything in that state.

Why does it enter this weird mode?

**Comment by landave** [comment]
What operating system, GPU, driver version are you running? How did you compile?

**Comment by Genhanktsti** [comment]
Windows 10, 1080 Ti, Game Ready Driver 436.02

I compiled it with Visual Studio 2019, Release, 64 Bit

**Comment by landave** [comment]
Okay. Can you reliably enter this state? And when it happens, do you eventually get out of it (e.g. by rebooting the machine)?

**Comment by MichaelDavidGK** [comment]
This happens when GPU is heavily undervolted/overclocked and/or driver crashes, nothing to fix there (sorry for bumping this, you can close it)
