### ISSUE TITLE
Poor performance (low hashrate and low GPU load) during computation on AMD Vega 56

### ISSUE THREAD

**Issue by Allesanddro** [landave/TeamSpeakHasher#17]
Seems like i have some issues over here on my 1060 6gb nvidia card it does work fine but with my 
amd vega 56 it doesnt utilize my gpu only in the tuning part it goes to 100% any clues? 

https://i.imgur.com/03VV6QC.png

**Comment by landave** [comment]
Try to set the global and local work size manually (in the ini, after tuning once), and then see what you get (run without -retune). For example, try the following values for global and local work size:

- (65536, 256)
- (65536, 128)
- (131072, 64)
- (131072, 128)
- (131072, 256)

**Comment by Allesanddro** [comment]
Nop tried all of them didn't work

**Comment by landave** [comment]
In the end, the hashing rate is what matters, and this seems to look normal. It is unclear what the "GPU Load" value in GPU-Z even means. Maybe you can read out stats with hwinfo64 and see what it says there.

**Comment by Allesanddro** [comment]
Even then its way to low for that gpu i will do check with hwinfo

**Comment by Allesanddro** [comment]
If u look at the powerdraw its literally nothing just idle power 

https://i.imgur.com/HU8Jn0g.png (65536, 256)
https://i.imgur.com/wvl0QtX.png (65536, 128)
https://i.imgur.com/nOASJbd.png (131072, 64)
https://i.imgur.com/0c1sMfH.png (131072, 128)
https://i.imgur.com/3b7XVRh.png (131072, 256)

**Comment by Allesanddro** [comment]
The thing is the gpu does go in a higher PState so it does try to do something but ya that hashrates r uhm compared to my nvid card (with less Compute units) bad

**Comment by landave** [comment]
In general, I would not care too much about the power/load values, since part of the GPU is just not stressed by TeamSpeakHasher (for example, the memory controller should stay essentially idle).

What hashrate are you getting with your GTX 1060?

**Comment by Allesanddro** [comment]
Around 2.7 GH/s

**Comment by Allesanddro** [comment]
https://i.imgur.com/6lfEUe8.png on the nvid it actually loads the core and gets a high power usage as comparison

**Comment by landave** [comment]
Okay, that seems to be normal.

I think you are right, the Vega56 should be faster. What OS Version and GPU driver are you using? How did you compile TeamspeakHasher?

**Comment by Allesanddro** [comment]
compiled via vs 19 with the amd opencl.lib 
windows version 1909 build 18363.836
drivers r 20.4.2 (also tried on the previous)

**Comment by landave** [comment]
Okay, that sounds good.

So you are saying that during the tuning phase, high load is achieved. What if you add a debug line to the tuning function to see what parameters are tested during tuning? For example, in TSHasherContext.cpp starting from line 310, we have the inner loop
```
while (globalsize <= max_global_work_size
           && duration_cast<milliseconds>(time).count() < 2000) {
      time_point<high_resolution_clock> starttime;

      for (size_t q = 0; q < 32; q++) {
```

Add the following line at the beginning of the loop:
```
std::cout << "localsize=" << localsize << ", globalsize=" << globalsize << std::endl;
```
So that is becomes:
```
while (globalsize <= max_global_work_size
           && duration_cast<milliseconds>(time).count() < 2000) {
      time_point<high_resolution_clock> starttime;
      std::cout << "localsize=" << localsize << ", globalsize=" << globalsize << std::endl;
      for (size_t q = 0; q < 32; q++) {
```

Then, retune and keep an eye on the load with hwinfo64.

**Comment by Allesanddro** [comment]
Will try

**Comment by Allesanddro** [comment]
thats the output i get C:\Users\sandr\source\repos\TeamSpeakHasher\Debug>TeamSpeakHasher.exe compute -retune
+----------------------------------------------------------+
|[ID]|Nickname|Current Counter|Best Counter|Best Difficulty|
+----------------------------------------------------------+
|0   |test    |15570035712    |0           |1              |
+----------------------------------------------------------+
Please select an identity: 0
Initializing OpenCL...
Found new device #0: gfx900, 56 compute units
  Tuning...
  localsize=16, globalsize=16
.localsize=16, globalsize=32
.localsize=16, globalsize=64
.localsize=16, globalsize=128
.localsize=16, globalsize=256
.localsize=16, globalsize=512
.localsize=16, globalsize=1024
.localsize=16, globalsize=2048
.localsize=16, globalsize=4096
.localsize=16, globalsize=8192
.localsize=16, globalsize=16384
.localsize=16, globalsize=32768
.localsize=16, globalsize=65536
.localsize=16, globalsize=131072
.localsize=32, globalsize=32
.localsize=32, globalsize=64
.localsize=32, globalsize=128
.localsize=32, globalsize=256
.localsize=32, globalsize=512
.localsize=32, globalsize=1024
.localsize=32, globalsize=2048
.localsize=32, globalsize=4096
.localsize=32, globalsize=8192
.localsize=32, globalsize=16384
.localsize=32, globalsize=32768
.localsize=32, globalsize=65536
.localsize=32, globalsize=131072
.localsize=32, globalsize=262144
.localsize=64, globalsize=64
.localsize=64, globalsize=128
.localsize=64, globalsize=256
.localsize=64, globalsize=512
.localsize=64, globalsize=1024
.localsize=64, globalsize=2048
.localsize=64, globalsize=4096
.localsize=64, globalsize=8192
.localsize=64, globalsize=16384
.localsize=64, globalsize=32768
.localsize=64, globalsize=65536
.localsize=64, globalsize=131072
.localsize=64, globalsize=262144
.

  Tuning found global_work_size=65536, local_work_size=64 to be optimal.


Initialization done, starting computation...

**Comment by Allesanddro** [comment]
https://i.imgur.com/mtX4WEY.png While Tuning 
https://i.imgur.com/sQxDZWL.png when it actually computes 
im not a specialist but maybe its a weird amd thing ? like why does it use a different compute core for tuning and a different one for computing

**Comment by landave** [comment]
This is an interesting observation. It really seems that something different is happening during tuning than during actual computation.

Can you change replace this instruction [(TSHasherContext.cpp:302)](https://github.com/landave/TeamSpeakHasher/blob/master/TSHasherContext.cpp#L302)
```
const size_t end_local_worksize = max_local_worksize > 128 ?
                                      std::max((size_t)1, max_local_worksize / 16)
                                      : max_local_worksize;
```
by simply
```
const size_t end_local_worksize = max_local_worksize;
```

Moreover, starting from [TSHasherContext.cpp:353](https://github.com/landave/TeamSpeakHasher/blob/master/TSHasherContext.cpp#L353)
```
uint64_t time_norm = time_ns / globalsize;

std::cout << ".";

if (time_norm < besttime) {
```
replace the instruction `std::cout << ".";` by
```
std::cout << "time_norm=" << time_norm << std::endl;
```

And then retune.

**Comment by Allesanddro** [comment]
C:\Users\sandr\source\repos\TeamSpeakHasher\Debug>TeamSpeakHasher.exe compute -retune
+----------------------------------------------------------+
|[ID]|Nickname|Current Counter|Best Counter|Best Difficulty|
+----------------------------------------------------------+
|0   |test    |153552873472   |36967192262 |35             |
+----------------------------------------------------------+
Please select an identity: 0
Initializing OpenCL...
Found new device #0: gfx900, 56 compute units
  Tuning...
  localsize=16, globalsize=16
time_norm=10512837
localsize=16, globalsize=32
time_norm=5251231
localsize=16, globalsize=64
time_norm=2625712
localsize=16, globalsize=128
time_norm=1318926
localsize=16, globalsize=256
time_norm=658122
localsize=16, globalsize=512
time_norm=328350
localsize=16, globalsize=1024
time_norm=165296
localsize=16, globalsize=2048
time_norm=108932
localsize=16, globalsize=4096
time_norm=68284
localsize=16, globalsize=8192
time_norm=49014
localsize=16, globalsize=16384
time_norm=28474
localsize=16, globalsize=32768
time_norm=22514
localsize=16, globalsize=65536
time_norm=20548
localsize=16, globalsize=131072
time_norm=19591
localsize=32, globalsize=32
time_norm=5335656
localsize=32, globalsize=64
time_norm=2670476
localsize=32, globalsize=128
time_norm=1332217
localsize=32, globalsize=256
time_norm=667561
localsize=32, globalsize=512
time_norm=333466
localsize=32, globalsize=1024
time_norm=166615
localsize=32, globalsize=2048
time_norm=83898
localsize=32, globalsize=4096
time_norm=55157
localsize=32, globalsize=8192
time_norm=34646
localsize=32, globalsize=16384
time_norm=24908
localsize=32, globalsize=32768
time_norm=15223
localsize=32, globalsize=65536
time_norm=12168
localsize=32, globalsize=131072
time_norm=11137
localsize=32, globalsize=262144
time_norm=10658
localsize=64, globalsize=64
time_norm=2730575
localsize=64, globalsize=128
time_norm=1356943
localsize=64, globalsize=256
time_norm=680330
localsize=64, globalsize=512
time_norm=340486
localsize=64, globalsize=1024
time_norm=170336
localsize=64, globalsize=2048
time_norm=84858
localsize=64, globalsize=4096
time_norm=42939
localsize=64, globalsize=8192
time_norm=21668
localsize=64, globalsize=16384
time_norm=14348
localsize=64, globalsize=32768
time_norm=9840
localsize=64, globalsize=65536
time_norm=8414
localsize=64, globalsize=131072
time_norm=10381
localsize=64, globalsize=262144
time_norm=10277
localsize=128, globalsize=128
time_norm=1379809
localsize=128, globalsize=256
time_norm=692303
localsize=128, globalsize=512
time_norm=345890
localsize=128, globalsize=1024
time_norm=172650
localsize=128, globalsize=2048
time_norm=86128
localsize=128, globalsize=4096
time_norm=42964
localsize=128, globalsize=8192
time_norm=28196
localsize=128, globalsize=16384
time_norm=14314
localsize=128, globalsize=32768
time_norm=9660
localsize=128, globalsize=65536
time_norm=9108
localsize=128, globalsize=131072
time_norm=10334
localsize=128, globalsize=262144
time_norm=10840
localsize=256, globalsize=256
time_norm=709469
localsize=256, globalsize=512
time_norm=354807
localsize=256, globalsize=1024
time_norm=176864
localsize=256, globalsize=2048
time_norm=88273
localsize=256, globalsize=4096
time_norm=43882
localsize=256, globalsize=8192
time_norm=22049
localsize=256, globalsize=16384
time_norm=14525
localsize=256, globalsize=32768
time_norm=9678
localsize=256, globalsize=65536
time_norm=8411
localsize=256, globalsize=131072
time_norm=10372
localsize=256, globalsize=262144
time_norm=10858
localsize=512, globalsize=512
A critical error occurred while enqueuing the kernel.

**Comment by landave** [comment]
Interesting! So it looks like the tuning is fine (except for a small bug in determining max_local_worksize causing it not to stop after 256 in this case; I will fix this), and you reach ~3.5GHash/s (if my math is right).

During the actual computation though, something weird happens. For now, you can revert the changes in the code (in particular, let it set the end_local_worksize as before). Give me a moment to think about the potential cause for this behavior.

**Comment by landave** [comment]
Can you try to run with `compute -throttle 0`?

**Comment by Allesanddro** [comment]
that did the trick

**Comment by Allesanddro** [comment]
https://i.imgur.com/uFZxpq3.png

**Comment by landave** [comment]
Awesome! Could you try to comment it back in and try a few smaller values than `0.9` (say, `0.85`, `0.8`, `.75`., `.7`, ...) until you get no performance hit anymore?

**Comment by Allesanddro** [comment]
will do gimme a sec

**Comment by Allesanddro** [comment]
well if its not 0 it wont go above 1.4 gh/s on 0 i get 4 gh/s 
![image](https://user-images.githubusercontent.com/23656101/83531355-2b5de680-a4ed-11ea-96ae-411f52a0814f.png)

**Comment by landave** [comment]
Wow, interesting. Thank you. What CPU are you running on, and what is the CPU usage during the computation with 0 sleep factor?

**Comment by Allesanddro** [comment]
Its a Ryzen 2700X on 4.2Ghz
![image](https://user-images.githubusercontent.com/23656101/83531749-a3c4a780-a4ed-11ea-9e92-278c20976490.png)

**Comment by landave** [comment]
Okay, so the CPU usage is essentially 0% even without sleeping at all. Could you try to see what happens on your NVIDIA system if you have 0 sleep factor? How is the hashing rate and how is the CPU usage there?

**Comment by Allesanddro** [comment]
Yep

**Comment by Allesanddro** [comment]
![image](https://user-images.githubusercontent.com/23656101/83532307-5d237d00-a4ee-11ea-84bc-ca285cf88c3d.png)
Uh thats a 20c/40t dual socket system

**Comment by landave** [comment]
Yes, so there it actually occupies a full CPU core (and the hashing rate does not really increase).

**Comment by Allesanddro** [comment]
Like i said im not a specialist but it might be that amd has 3 different compute"Cores" to use instead nvidia just using the cuda api no clue tbh maybe u understand what i mean ^^

**Comment by landave** [comment]
An interesting difference is that on the AMD system, we schedule about 60 kernels per second, and only 10 on the NVIDIA system. This means that with a fixed constant sleep factor, the sleep time (as implemented right now) is much smaller on the AMD system (~15ms vs. ~90ms).

But surprisingly, even with the sleep enabled (see your very first screenshot), we still schedule 10.1 (instead of 9.5) kernels per second, at the same local/global work sizes! This indicates that the sleep should slow us down only by less than 10 percent (not 90 percent!). Something is not right here...

**Comment by Allesanddro** [comment]
Strange ngl

**Comment by Allesanddro** [comment]
Well since it works fine how it is rn i will close this issue :)

**Comment by landave** [comment]
I just pushed some changes to address this problem. The tuning is also slightly updated.

Could you try the current version (without any manual modifications) and test whether everything works as expected? In particular, it would be great if you could retune and then check the hash rate, GPU load, and also the CPU load.

**Comment by Allesanddro** [comment]
![image](https://user-images.githubusercontent.com/23656101/83715569-fb6a2c80-a62d-11ea-80a0-d4e8d9bb9e83.png)
Seems to work

**Comment by landave** [comment]
Perfect, thank you.
