### ISSUE TITLE
OpenCL.lib

### ISSUE THREAD

**Issue by TheColin21** [landave/TeamSpeakHasher#20]
I am currently trying to find suitable OpenCL.lib files for my AMD Vega64 GPU. Are there any reliable sources?

**Comment by landave** [comment]
This seems to be used by many: [https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/releases]()

I wonder why I cannot find a proper official source though...

**Comment by TheColin21** [comment]
Thanks, this looks a bit better than the versions from some old AMD App SDK that I used yesterday.

Am 27. Dezember 2020 12:50:08 MEZ schrieb landave <notifications@github.com>:

**Comment by TheColin21** [comment]
The tool works great by the way. Just pushed my level to 45 in practically no time.

Am 27. Dezember 2020 12:50:08 MEZ schrieb landave <notifications@github.com>:
