### ISSUE TITLE
Pre Built version

### ISSUE THREAD

**Issue by RunDavidMC** [landave/TeamSpeakHasher#21]
Hi, can you provide a pre-built version for Windows? I'm having trouble building myself.

**Comment by SapuSeven** [comment]
As described in #22, I've set up a simple CI pipeline with my fork.

You can download the latest Windows release [here](https://github.com/SapuSeven/TeamSpeakHasher/actions/workflows/build-windows.yml).

**Comment by RunDavidMC** [comment]
Ok, thank you. Could you also provide a Linux version if possible?

**Comment by NotActuallyTerry** [comment]
Please be aware that artifacts generated by actions do expire, so for permanently-available builds setting up a release is a good idea.
Could you re-open this @landave

**Comment by mrbesen** [comment]
maybe just add some binarys as relase?

**Comment by landave** [comment]
Thanks for the hint. I just triggered a new release.
