### ISSUE TITLE
Hardware usage?

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#3]
I have a question about what hardware is being used. As far as i read and heard openCL uses either CPU or GPU depending on what has more power but it doesn't utilize both at the same time, is that correct so far?

Also when running it on my machine the "reported device" by TeamspeakHasher is
```ini
[tunedparameter]
devicename=Caicos
deviceidentifier=Caicos_Advanced_Micro_Devices__Inc__4098_OpenCL_1_2_AMD_APP__1800_11__1800_11__VM__0
localworksize=16
globalworksize=512
```
Is that my CPU (AMD FX 4300) or GPU (AMD Radeon R5 200) now? 😕

**Comment by landave** [comment]
From the FAQ:
> Currently, only GPUs are supported. This is mainly due to the current code not being vectorized properly. However, OpenCL also supports CPUs. You can try to change DEV_TYPE in TSHasherContext.h to CL_DEVICE_TYPE_CPU.

**Comment by Bluscream** [comment]
So Caicos is the "internal?" name of my Radeon GPU? Or some generic driver name? 🤔

**Comment by landave** [comment]
Yes, Caicos is the name of your AMD GPU.

**Comment by Bluscream** [comment]
Okay thanks!
