### ISSUE TITLE
Get more power?

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#4]
When running TeamspeakHasher i usually get around 20-40% CPU load with an average of 1.098184 MHash/s. This leaves my PC usable but feels like wasted time when i want to leave my PC hashing overnight while i'm sleeping. Even when using `TeamspeakHasher.exe compute -throttle 0` doesn't increase the load.

![](https://i.imgur.com/r7d4x9r.png)

On the other hand while using [Hashdog](http://yat.qa/ressourcen/sicherheitsstufe/#Geht+das+nicht+schneller%3F) my PC indeed starts lagging out completely with 100% CPU load. It feels faster but as it's only using the CPU i'm not sure if it's faster after all

**Comment by landave** [comment]
The tool puts the load on the GPU only (the CPU load is due to the scheduling costs of the OpenCL runtime and some verification computations).

1MashH/s is pretty slow, which is to be expected with such a low-end GPU (AMD Radeon R5 200). Current high-end GPUs easily do multiple GHash/s.

**Comment by Bluscream** [comment]
So with such a low-end GPU you suggest using the CPU instead?

**Comment by landave** [comment]
I would guess that your CPU does about 1-2 MHash/s as well.

Anything significantly below 1GHash/s is just a waste of energy, since it will take you years to reach a level that someone with a proper GPU reaches within minutes.

**Comment by Bluscream** [comment]
OT: i had a GT 740 (still lays on top of my rig) but i fried it so i had to switch to something i had lying around.

As always thanks for your answers and help 👍

**Comment by Bluscream** [comment]
Looks like it's not even utilizing the GPU that much at all

![](https://i.imgur.com/lQBbqNS.png)

**Comment by landave** [comment]
You should read out these values with a tool like HWiNFO64.

**Comment by Bluscream** [comment]
Hmm, doesn't look any better

![](https://i.imgur.com/96mm9IL.png)

**Comment by Bluscream** [comment]
Even with HWinfo set to use the AMD drivers values instead of it's own methods still not much:
![](https://i.imgur.com/95TuunR.png)

**Comment by landave** [comment]
It seems that with these old GPUs, you cannot read the desired values properly. That doesn't really matter, it's probably fine.

**Comment by Bluscream** [comment]
With the mixed devices it works a LOT better :)

![](https://i.imgur.com/EP6wLFu.png)
