### ISSUE TITLE
Suggested openCL library?

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#5]
I have compiled TeamspeakHasher using https://github.com/GPUOpen-Tools/common-lib-amd-APPSDK-3.0/tree/master/3-0/lib are these the suggested ones? Or are there no updates to it/version differences?

**Comment by landave** [comment]
Looks good to me.

**Comment by Bluscream** [comment]
I understand that you can't ship them with the project because of copyright issues but it might make sense to link some tested x86/x64 pair in the README to avoid confusion with all the different ones provided by a google search :)
