### ISSUE TITLE
Re-imported ID shows lvl 0

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#6]
I tried to re-import multiple ID's with their "new" offsets after getting higher sec levels with TeamspeakHasher but they always show up as either lvl 0 or 1 :/

![](https://i.imgur.com/cdJI37u.png)

I just changed the part between `="` and the first `V` with the counter of the last sec lvl
![](https://i.imgur.com/Is7NvPU.png)

**Comment by landave** [comment]
Please present a full example of this. What is the content of the ini file? What is the content of tshasher.ini?

**Comment by Bluscream** [comment]
Original exported `e3dvocUFTE1UWIvtW8qzulnWErI=.ini` with level **30**:
```ini
[Identity]
id="e3dvocUFTE1UWIvtW8qzulnWErI="
identity="30054583VZTW8Whnx42..."
nickname=aMW|Bluscream
phonetic_nickname=
```
`tshasher.ini`:
```ini
...
[identity]
nickname=e3dvocUFTE1UWIvtW8qzulnWErI=
identity=MEwDAgcAAgEgAiEA7pcSTL\/0KIdQyWFmRf9sr72uRQ\/\/AOy8LFA\/CQWX49UCIGW+lJbWoEdDklcjhmuTSqd+uPIGjrpEanetJ4atheA2
currentcounter=30054583
bestcounter=676032480
...
```
New imported `e3dvocUFTE1UWIvtW8qzulnWErI=.ini` with level **32**:
```ini
[Identity]
id="e3dvocUFTE1UWIvtW8qzulnWErI="
identity="676032480VZTW8W..."
nickname=aMW|Bluscream
phonetic_nickname=
```

**Comment by landave** [comment]
Please generate an identity for testing purposes only, so that you can paste the full private key.

**Comment by Bluscream** [comment]
1. Original exported `dDoUh6ZxyCPCCnLkDOiyOb6G9Es=.ini` with level **8**:
```ini
[Identity]
id=landave
identity="507V2G1QIPrmHRk0cIzQaMrhm8m7CidXIlMEaHpYeVVwYFNddmJ0eB1mKDEAUwlRJXtZLUVIHR9LSQpRY0cie3oFYVoEXF9BF1J/FVd8LidOCQxfekBHKlZZBxhTXGZ6BkJ8MnoPQU9QNC9BaUVBK2Iza1p6SXVpVUVkckVjcE5ReTBTL0dSMEZyV1NLanFpNEhNQ09YU3hDdz0="
nickname=landave
phonetic_nickname=
```
2. Getting the public key (omega):
```
[OUT] clientinitiv alpha=n+doBjldXoTeKQ== omega=MEwDAgcAAgEgAiEAu8YYbDb4QN9H6AUf8AVCK/QJR25ldANhNpy//yzl4VsCIB5Sj5lourkOt3MJF/hinJwrNcje/7iQKeqLWJ9rOP4/ ot=1 ip=XXX.XX.XXX.XXX
```
3. Validating the omega:
![](https://i.imgur.com/URUhtOX.png)

4. Adding the ID:
```
PS C:\Users\blusc\source\repos\TeamSpeakHasher\x64\Release> .\TeamSpeakHasher.exe add -publickey MEwDAgcAAgEgAiEAu8YYbDb4QN9H6AUf8AVCK/QJR25ldANhNpy//yzl4VsCIB5Sj5lourkOt3MJF/hinJwrNcje/7iQKeqLWJ9rOP4/ -startcounter 507 -nickname dDoUh6ZxyCPCCnLkDOiyOb6G9Es=
Public key has been added successfully.
```
5. `tshasher.ini` before hashing:
```ini
...
[identity]
nickname=dDoUh6ZxyCPCCnLkDOiyOb6G9Es=
identity=MEwDAgcAAgEgAiEAu8YYbDb4QN9H6AUf8AVCK/QJR25ldANhNpy//yzl4VsCIB5Sj5lourkOt3MJF/hinJwrNcje/7iQKeqLWJ9rOP4/
currentcounter=507
bestcounter=507
...
```
5. Initial hashing:
```
Running time: 6.013608 s
Device Caicos[0]:
  Global/Local work size: 512/16
  Current speed: 4.766212 MHash/s
  Average speed: 5.585795 MHash/s
  Scheduling: 11.1414 Kernels/s
Current speed [total]: 4.766212 MHash/s
Average speed [total]: 5.585795 MHash/s
Estimated time until slow phase: 58280.620573 h
Security level: 8 (with counter=507)
Estimated time until level 32: 15.018802 min
Current counter: 34117248
```
5.1 After two minutes (still at **8** for some reason :/ ):
```
Running time: 2.344241 min
Device Caicos[0]:
  Global/Local work size: 512/16
  Current speed: 847495.267172 Hash/s
  Average speed: 1.445261 MHash/s
  Scheduling: 2.77986 Kernels/s
Current speed [total]: 847495.267172 Hash/s
Average speed [total]: 1.445261 MHash/s
Estimated time until slow phase: 327763.153287 h
Security level: 8 (with counter=507)
Estimated time until level 32: 1.407732 h
Current counter: 203809024
```
6. Stopped hashing:
```

```

**Comment by landave** [comment]
Looks good to me. The minimum level is fixed to 32, because with decent GPUs, this is found within less than a second. So you need to wait a bit until level 32 is reached.

**Comment by Bluscream** [comment]
Let's see when i can even finish my comment; for now i'm stuck with 8

```
Running time: 15.360146 min
Device Caicos[0]:
  Global/Local work size: 512/16
  Current speed: 473069.292723 Hash/s
  Average speed: 696728.925940 Hash/s
  Scheduling: 1.33245 Kernels/s
Current speed [total]: 473069.292723 Hash/s
Average speed [total]: 696728.925940 Hash/s
Estimated time until slow phase: 587181.631517 h
Security level: 8 (with counter=507)
Estimated time until level 32: 2.521928 h
Current counter: 643162368
```

**Comment by Bluscream** [comment]
What does minimum mean for you? It will only show the "new" offset when 32 has been "reached"/"found"?

**Comment by landave** [comment]
Yes, the tool will ignore counters that result in a security level lower than 32. This is a performance optimization.

**Comment by Bluscream** [comment]
So it completely skips these levels? Wouldn't it make sense to define a starting level then? If you don't want to get below 108 for example?

**Comment by landave** [comment]
The purpose of this lower bound is mostly that we don't find new counters too fast and then have to reschedule new kernels. Moreover, this allows to simplify the check of newly computed hashes within the kernels on the GPU.

Having a higher bound will not yield a significant improvement.

**Comment by Bluscream** [comment]
Okay i updated https://github.com/landave/TeamSpeakHasher/issues/6#issuecomment-377396347

Aaand i think i found the fault being the escaping of `/` with `\/` in the public keys 😠 

Lemme quickly confirm and close this

**Comment by Bluscream** [comment]
Yes, that was it i'm so sorry ;_;

![](https://i.imgur.com/F1a5zgw.png)
