### ISSUE TITLE
UID

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#7]
I'd have the suggestion to also calculate the UID (or fingerprint if you prefer so) and show it in the `compute` list and while hashing so you don't have to completely depend on the nickname and can use an actual nickname there. Tho i'm not sure if the private key is required to calculate the UID :o

**Comment by landave** [comment]
The fingerprint is computed from the public key only, so this would be possible. However, I don't see great value in this feature. You can just include the fingerprint in the nickname if this is important to you.

**Comment by Bluscream** [comment]
I did already, thanks for your opinion :)

```
+------------------------------------------------------------------------------+
|[ID]|Nickname                    |Current Counter|Best Counter|Best Difficulty|
+------------------------------------------------------------------------------+
|0   |9NvkFRYwomVgDYKdfeyTHFIWDoM=|915267840      |742977759   |32             |
|1   |eVAaW2DkZC8qhLLM2io3xP4NjxM=|284064815      |284064815   |0              |
|2   |e3dvocUFTE1UWIvtW8qzulnWErI=|30054583       |30054583    |2              |
|3   |x63jNGErPXnu9l3bFECzMzWfXk= |12031902       |12031902    |28             |
+------------------------------------------------------------------------------+
```
