### ISSUE TITLE
Manually tweak usage?

### ISSUE THREAD

**Issue by Bluscream** [landave/TeamSpeakHasher#8]
I know of compute `throttle <int>`

Can you explain the ini values a bit and how one tweaks the resource consumption with them? especially `localworksize` and `globalworksize`

```ini
[tunedparameter]
devicename=Caicos
deviceidentifier=Caicos_Advanced_Micro_Devices__Inc__4098_OpenCL_1_2_AMD_APP__1800_11__1800_11__VM__0
localworksize=16
globalworksize=512
```

**Comment by landave** [comment]
`localworksize` and `globalworksize` are the two values that are passed to the OpenCL API. You can look this up in the [OpenCL Documentation](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clEnqueueNDRangeKernel.html).

Depending on your actual computing device (e.g., your GPU), different work sizes are possible. TeamspeakHasher tries to find a good choice for these values in the initial tuning phase.

**Comment by Bluscream** [comment]
Thanks :)
